//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.rs;

import com.hp.sdn.rs.misc.ControllerResource;

import javax.ws.rs.Path;

/**
 * Sample Blacklist REST API resource.
 */
@Path("blacklist")
public class BlacklistResource extends ControllerResource {

}
