//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.model;

import static org.junit.Assert.*;

import org.junit.Test;

import java.util.UUID;

import com.hp.api.Id;

/**
 * Sample test of the TestApp domain model.
 */
public class TestAppTest {

    @Test
    public void basic() {
        Id<TestApp, UUID> id = Id.valueOf(UUID.randomUUID());
        TestApp s = new TestApp(id, "Gizmo");
        assertEquals("incorrect id", id, s.getId());
        assertEquals("incorrect name", "Gizmo", s.name());
    }

}
