//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.api;

import java.util.Collection;
import java.util.UUID;

import com.hp.api.Id;
import com.tallac.blacklist.model.Blacklist;

/**
 * Sample Blacklist service interface.
 */
public interface BlacklistService {

   
    public void enableBlacklist();
    public void disableBlacklist();
    public boolean isBlacklistEnabled();

}
