//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.impl;

import com.tallac.blacklist.api.BlacklistService;

/**
 * Sample test of the Blacklist service implementation.
 */
public class BlacklistManagerTest {
  
    private BlacklistService svc;

}
