//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.ui.rs;

import static org.easymock.EasyMock.createMock;

import java.util.Collections;

import javax.ws.rs.core.MediaType;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.hp.util.rs.ResourceTest;
import com.hp.sdn.rs.misc.ControllerResourceTest;

import com.tallac.blacklist.api.BlacklistService;


/**
 * Sample Blacklist REST API resource.
 */
public class BlacklistResourceTest extends ControllerResourceTest {

    private BlacklistService svc;
    
    /**
     * Creates a test suite on the default package set.
     */
    public BlacklistResourceTest() {
        super("com.tallac.blacklist.ui.rs");
    }
    

    @Override
    @Before
    public void setUp() throws Exception {
        super.setUp();
        svc = createMock(BlacklistService.class);

        sl.register(BlacklistService.class, svc,
                    Collections.<String, Object> emptyMap());

        // If a specific test case expects a different format, such
        // format will have to be set calling this method.
        ResourceTest.setDefaultMediaType(MediaType.APPLICATION_JSON);
    }
    
    @Override
    @After
    public void tearDown() throws Exception {
        super.tearDown();
        sl.unregister(BlacklistService.class, svc);
    }   

    @Test
    public void hello() {
        String r = get("blacklist");
        assertResponseContains(r, "The world is all about Blacklist");
    }

}
