//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.rs;

import com.hp.sdn.rs.misc.ControllerResourceTest;


/**
 * Sample TestApp REST API resource.
 */
public class TestAppResourceTest extends ControllerResourceTest {

}
