//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.acme.lab.model;

import java.util.UUID;

import com.hp.api.Id;
import com.hp.sdn.Model;

/**
 * Sample SdnLab domain model.
 */
public class SdnLab extends Model<SdnLab> {

    private static final long serialVersionUID = 7571309040451072286L;

    // Just to make the sample a bit more interesting.
    private String name;

    /** 
     * Default constructor required for serialization.
     */
    public SdnLab() {
        super();
    }

    /** 
     * Creates a new SdnLab entity. 
     *
     * @param name SdnLab name
     */
    public SdnLab(String name) {
        super();
        this.name = name;
    }

    /** 
     * Creates a new SdnLab entity. 
     *
     * @param id SdnLab unique id
     * @param name SdnLab name
     */
    public SdnLab(Id<SdnLab, UUID> id, String name) {
        super(id);
        this.name = name;
    }
    
    /**
     * Get the SdnLab name.
     *
     * @return SdnLab name
     */
    public String name() {
        return name;
    }

    /**
     * Set the SdnLab name.
     *
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }
}
