//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.acme.lab.model;

/**
 * SdnLab sort attribute.
 */
public enum SdnLabSortAttribute {

    /** Sorts by name */
    NAME

}
