//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.acme.lab.rs;

import com.hp.sdn.rs.misc.ControllerResourceTest;


/**
 * Sample SdnLab REST API resource.
 */
public class SdnLabResourceTest extends ControllerResourceTest {

}
