//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.impl;

/**
 * Sample test of the TestApp service implementation.
 */
public class TestAppManagerTest {
  
}
