//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.api;

/**
 * Sample TestApp service interface.
 */
public interface TestAppService {

    /**
     * Get all TestApp items.
     *
     * @return collection of all TestApp items
     */
//    public Collection<TestApp> getAll();

    /** 
     * Creates a new TestApp entity.
     *
     * @param id unique id to be assigned to the new TestApp entity.
     * @param name TestApp name
     * @return newly created TestApp
     */
//    public TestApp create(String name);

    /**
     * Get the TestApp with the specified unique id.
     *
     * @param uid unique id of the TestApp entity to be retrieved
     * @return TestApp with the given unique id
     * @throws NotFoundException if the requested TestApp was not found
     */
//    public TestApp get(Id<TestApp, UUID> id);

    /**
     * Delete the TestApp with the specified id.
     *
     * @param uid unique id of the TestApp entity to be deleted
     * @return deleted TestApp
     * @throws NotFoundException if the requested TestApp was not found
     */
//    public void delete(Id<TestApp, UUID> id);

}
