//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.rs;

import com.hp.sdn.rs.misc.ControllerResourceTest;

/**
 * Sample Blacklist REST API resource.
 */
public class BlacklistResourceTest extends ControllerResourceTest {

}
