//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.acme.lab.impl;

import com.acme.lab.api.SdnLabService;
import com.hp.of.ctl.ControllerService;

import org.apache.felix.scr.annotations.Activate;
import org.apache.felix.scr.annotations.Component;
import org.apache.felix.scr.annotations.Deactivate;
import org.apache.felix.scr.annotations.Reference;
import org.apache.felix.scr.annotations.ReferenceCardinality;
import org.apache.felix.scr.annotations.ReferencePolicy;
import org.apache.felix.scr.annotations.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Sample SdnLab service implementation.
 */
@Component(metatype=true)
@Service
public class SdnLabManager implements SdnLabService {

    @Reference(policy = ReferencePolicy.DYNAMIC, cardinality = ReferenceCardinality.MANDATORY_UNARY)
    private volatile ControllerService controllerService;
    
	private static final Logger LOG = LoggerFactory.getLogger( SdnLabManager.class );
	
	@Activate
	protected void activate()
	{
		LOG.info( "MySdnLab: activated" );
	}
	
	@Deactivate
	protected void deactivate()
	{
		LOG.info( "MySdnLab: deactivated" );
	}

}
