//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.model;

import static org.junit.Assert.*;

import org.junit.Test;

import java.util.UUID;

import com.hp.api.Id;

/**
 * Sample test of the Blacklist domain model.
 */
public class BlacklistTest {

    @Test
    public void basic() {
        Id<Blacklist, UUID> id = Id.valueOf(UUID.randomUUID());
        Blacklist s = new Blacklist(id, "Gizmo");
        assertEquals("incorrect id", id, s.getId());
        assertEquals("incorrect name", "Gizmo", s.name());
    }

}
