//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.rs;

import com.hp.sdn.rs.misc.ControllerResource;

import javax.ws.rs.Path;

/**
 * Sample TestApp REST API resource.
 */
@Path("cb")
public class TestAppResource extends ControllerResource {


}
