//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.acme.lab.impl;

/**
 * Sample test of the SdnLab service implementation.
 */
public class SdnLabManagerTest {
  
}
