//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.model;

/**
 * Blacklist sort attribute.
 */
public enum BlacklistSortAttribute {

    /** Sorts by name */
    NAME

}
