//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.blacklist.model;

import java.util.UUID;

import com.hp.api.Id;
import com.hp.api.Transportable;
import com.hp.sdn.BaseModel;
import com.hp.sdn.auditlog.AuditLogEntry;
import com.hp.sdn.Model;

/**
 * Sample Blacklist domain model.
 */
public class Blacklist extends Model<Blacklist> {

    private static final long serialVersionUID = 7571309040451072286L;

    // Just to make the sample a bit more interesting.
    private String name;

    /** 
     * Default constructor required for serialization.
     */
    public Blacklist() {
        super();
    }

    /** 
     * Creates a new Blacklist entity. 
     *
     * @param name Blacklist name
     */
    public Blacklist(String name) {
        super();
        this.name = name;
    }

    /** 
     * Creates a new Blacklist entity. 
     *
     * @param id Blacklist unique id
     * @param name Blacklist name
     */
    public Blacklist(Id<Blacklist, UUID> id, String name) {
        super(id);
        this.name = name;
    }
    
    /**
     * Get the Blacklist name.
     *
     * @return Blacklist name
     */
    public String name() {
        return name;
    }

    /**
     * Set the Blacklist name.
     *
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }
}
