//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.acme.lab.rs;

import com.hp.sdn.rs.misc.ControllerResource;

import javax.ws.rs.Path;

/**
 * Sample SdnLab REST API resource.
 */
@Path("SdnLab")
public class SdnLabResource extends ControllerResource {

}
