//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.model;

import java.util.UUID;

import com.hp.api.Id;
import com.hp.sdn.Model;

/**
 * Sample TestApp domain model.
 */
public class TestApp extends Model<TestApp> {

    private static final long serialVersionUID = 7571309040451072286L;

    // Just to make the sample a bit more interesting.
    private String name;

    /** 
     * Default constructor required for serialization.
     */
    public TestApp() {
        super();
    }

    /** 
     * Creates a new TestApp entity. 
     *
     * @param name TestApp name
     */
    public TestApp(String name) {
        super();
        this.name = name;
    }

    /** 
     * Creates a new TestApp entity. 
     *
     * @param id TestApp unique id
     * @param name TestApp name
     */
    public TestApp(Id<TestApp, UUID> id, String name) {
        super(id);
        this.name = name;
    }
    
    /**
     * Get the TestApp name.
     *
     * @return TestApp name
     */
    public String name() {
        return name;
    }

    /**
     * Set the TestApp name.
     *
     * @param name new name
     */
    public void setName(String name) {
        this.name = name;
    }
}
