//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.model;

/**
 * TestApp sort attribute.
 */
public enum TestAppSortAttribute {

    /** Sorts by name */
    NAME

}
