//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.tallac.cb.impl;

import com.hp.of.ctl.ControllerService;
import com.tallac.cb.api.TestAppService;
import com.tallac.cb.listener.PacketListener;
import com.tallac.cb.listener.SwitchListener;


import org.apache.felix.scr.annotations.Activate;
import org.apache.felix.scr.annotations.Component;
import org.apache.felix.scr.annotations.Deactivate;
import org.apache.felix.scr.annotations.Reference;
import org.apache.felix.scr.annotations.ReferenceCardinality;
import org.apache.felix.scr.annotations.ReferencePolicy;
import org.apache.felix.scr.annotations.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Sample TestApp service implementation.
 */
@Component(metatype=true)
@Service
public class TestAppManager implements TestAppService {

    @Reference(policy = ReferencePolicy.DYNAMIC, cardinality = ReferenceCardinality.MANDATORY_UNARY)
    private volatile ControllerService controllerService;
    
	private static final Logger LOG = LoggerFactory.getLogger( TestAppManager.class );
	
	private SwitchListener switchListener;
	private PacketListener packetListener;
	
	@Activate
	protected void activate()
	{
		LOG.info( "MyBlacklist: activate-stupid" );
		
		switchListener = new SwitchListener();
		switchListener.init( controllerService );
		switchListener.startup();
		
		packetListener = new PacketListener();
		packetListener.init( controllerService );
		packetListener.startup();

	}
	
	@Deactivate
	protected void deactivate()
	{
		LOG.info( "MyBlacklist: deactivate" );
		
		switchListener.shutdown();
		packetListener.shutdown();
		
		
	}
}
